#@data/values-schema
#@schema/desc "Deployment schema for the CAT+ ChemBoard frontend"
---
name: 'catplus-chemboard'
version: 'latest'
namespace: 'chemboard'

image:
  repository: 'ghcr.io/sdsc-ordes/catplus-chemboard'
  tag: 'latest'
  pullPolicy: 'Always'

s3:
  #@schema/desc "Name of existing secret containing all S3 configuration. If provided, fields below will be ignored."
  #@schema/example "my-s3-credentials"
  #@schema/nullable
  existingSecret: ''
  region: ''
  #@schema/desc "Custom (non-AWS) S3 endpoint URL"
  #@schema/example "https://s3.custom-endpoint.example.com"
  endpoint: ''
  bucketName: ''
  accessKeyId: ''
  secretAccessKey: ''

service:
  port: 80

ingress:
  #@schema/desc "Whether to create an Ingress resource"
  enabled: true
  #@schema/desc "Hostname for the ingress"
  #@schema/example "chemboard.example.com"
  host: ''
  #@schema/desc "Path prefix for the ingress rule"
  path: '/'
  #@schema/desc "Path type for the ingress rule (Exact, Prefix, or ImplementationSpecific)"
  pathType: 'Prefix'
  #@schema/desc "Ingress class name"
  className: 'nginx'
  #@schema/nullable
  annotations: {}
  tls:
    #@schema/desc "Whether to enable TLS for the ingress"
    enabled: true
    #@schema/desc "Name of the TLS secret"
    #@schema/nullable
    secretName: ''
