#@ load("@ytt:data", "data")

#@data/values
---
name: catplus-chemboard
version: latest
namespace: chemboard

image:
  repository: ghcr.io/sdsc-ordes/catplus-chemboard
  tag: latest
  pullPolicy: Always

s3:
  region: us-east-1
  endpoint: https://s3.custom-endpoint.example.com
  bucketName: catplus-chemboard-bucket
  existingSecret: '' #! Name of existing Kubernetes secret containing AWS credentials
  accessKeyId: ''
  secretAccessKey: ''

service:
  port: 80

ingress:
  host: chemboard.example.com
