#@ load("@ytt:data", "data")

apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ data.values.name + "-config"
  namespace: #@ data.values.namespace
  labels:
    app: #@ data.values.name
data:
  #! Application environment
  NODE_ENV: 'production'
  PORT: '3000'
  HOST: '0.0.0.0'

  #! AWS S3 config
  AWS_REGION: #@ data.values.s3.region
  AWS_S3_ENDPOINT: #@ data.values.s3.endpoint
  S3_BUCKET_NAME: #@ data.values.s3.bucketName
