#@ load("@ytt:data", "data")
#@ load("lib/common.star", "s3_secret_name")

#@ if not data.values.s3.existingSecret:
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.name + "-secrets"
  namespace: #@ data.values.namespace
  labels:
    app: #@ data.values.name
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: #@ data.values.s3.accessKeyId
  AWS_SECRET_ACCESS_KEY: #@ data.values.s3.secretAccessKey
#@ end