#@ load("@ytt:data", "data")

#@ def ingress_annotations():
#@   if hasattr(data.values.ingress, "annotations") and data.values.ingress.annotations:
#@     return data.values.ingress.annotations
#@   else:
#@     return {
#@       "kubernetes.io/ingress.class": data.values.ingress.className,
#@       "nginx.ingress.kubernetes.io/ssl-redirect": "true"
#@     }
#@   end
#@ end

#@ def tls_secret_name():
#@   if hasattr(data.values.ingress.tls, "secretName") and data.values.ingress.tls.secretName:
#@     return data.values.ingress.tls.secretName
#@   else:
#@     return data.values.name + "-tls"
#@   end
#@ end

#@ if data.values.ingress.enabled:
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: #@ data.values.name
  namespace: #@ data.values.namespace
  labels:
    app: #@ data.values.name
  annotations: #@ ingress_annotations()
spec:
  #@ if data.values.ingress.className:
  ingressClassName: #@ data.values.ingress.className
  #@ end
  rules:
  - host: #@ data.values.ingress.host
    http:
      paths:
      - path: #@ data.values.ingress.path
        pathType: #@ data.values.ingress.pathType
        backend:
          service:
            name: #@ data.values.name
            port:
              number: #@ data.values.service.port
  #@ if data.values.ingress.tls.enabled:
  tls:
  - hosts:
    - #@ data.values.ingress.host
    secretName: #@ tls_secret_name()
  #@ end
#@ end