#@ load("@ytt:data", "data")
#@ load("lib/common.star", "s3_secret_name")

#@ if not data.values.s3.existingSecret:
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.name + "-secrets"
  namespace: #@ data.values.namespace
  labels:
    app: #@ data.values.name
type: Opaque
stringData:
  region: #@ data.values.s3.region
  endpoint: #@ data.values.s3.endpoint
  bucketName: #@ data.values.s3.bucketName
  accessKeyId: #@ data.values.s3.accessKeyId
  secretAccessKey: #@ data.values.s3.secretAccessKey
#@ end